// Mock Product Database
const products = [
    // 🔹 ELECTRONICS (Apple, Samsung, Sony)
    {
        id: 'p1',
        name: 'Apple iPhone 15 Pro',
        brand: 'Apple',
        price: 1199.99,
        description: 'Flagship smartphone with A17 Pro chip and titanium design.',
        imageUrl: 'https://m.media-amazon.com/images/I/71d7rfSl0wL.jpg',
        category: 'Electronics',
        stock: 50,
    },
    {
        id: 'p2',
        name: 'Apple MacBook Air M3',
        brand: 'Apple',
        price: 1299.99,
        description: 'Lightweight laptop with M3 chip and stunning Retina display.',
        imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
        category: 'Electronics',
        stock: 40,
    },
    {
        id: 'p3',
        name: 'Apple AirPods Pro 2',
        brand: 'Apple',
        price: 249.99,
        description: 'Noise-cancelling wireless earbuds with adaptive transparency.',
        imageUrl: 'https://www.jiomart.com/images/product/original/493839243/apple-airpods-pro-2nd-gen-usb-c-type-with-magsafe-charging-case-true-wireless-with-active-noise-cancellation-touch-control-ip54-dust-sweat-and-water-resistant-bluetooth-v5-3-upto-30-hrs-of-playtime-white-digital-o493839243-p604564143-7-202509031818.jpeg?im=Resize=(420,420)',
        category: 'Electronics',
        stock: 100,
    },
    {
        id: 'p4',
        name: 'Samsung Galaxy S24 Ultra',
        brand: 'Samsung',
        price: 1099.99,
        description: 'Flagship Android smartphone with 200MP camera and S Pen.',
        imageUrl: 'https://www.myg.in/images/detailed/74/1_koh3-3z-removebg-preview.png',
        category: 'Electronics',
        stock: 60,
    },
    {
        id: 'p5',
        name: 'Samsung Galaxy Buds 2 Pro',
        brand: 'Samsung',
        price: 199.99,
        description: 'Hi-Fi sound wireless earbuds with ANC and 360 Audio.',
        imageUrl: 'https://m.media-amazon.com/images/I/61KVX-MbIUL.jpg',
        category: 'Electronics',
        stock: 120,
    },
    {
        id: 'p6',
        name: 'Sony WH-1000XM5 Headphones',
        brand: 'Sony',
        price: 349.99,
        description: 'Industry-leading noise-cancelling over-ear headphones.',
        imageUrl: 'https://m.media-amazon.com/images/I/61ULAZmt9NL.jpg',
        category: 'Electronics',
        stock: 80,
    },
    {
        id: 'p7',
        name: 'Sony PlayStation 5',
        brand: 'Sony',
        price: 499.99,
        description: 'Next-gen gaming console with lightning-fast SSD and DualSense controller.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZKccPuGE5lnRRTiQQmYVLvCWeE6ZVODNLYw&s',
        category: 'Electronics',
        stock: 35,
    },
    {
        id: 'p8',
        name: 'Sony Alpha ZV-E10 Camera',
        brand: 'Sony',
        price: 699.99,
        description: 'Compact 4K mirrorless camera for vlogging and photography.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3bn0uUjSM5Ozcm713NVEdXxAi0XvjeA7Srg&s',
        category: 'Electronics',
        stock: 45,
    },

    // 🔹 FASHION (Nike, Adidas)
    {
        id: 'p9',
        name: 'Nike Air Max 270',
        brand: 'Nike',
        price: 149.99,
        description: 'Stylish running shoes with Max Air cushioning.',
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
        category: 'Fashion',
        stock: 90,
    },
    {
        id: 'p10',
        name: 'Nike Dri-FIT Tee',
        brand: 'Nike',
        price: 39.99,
        description: 'Breathable t-shirt made with moisture-wicking fabric.',
        imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
        category: 'Fashion',
        stock: 150,
    },
    {
        id: 'p11',
        name: 'Nike Tech Fleece Hoodie',
        brand: 'Nike',
        price: 89.99,
        description: 'Premium hoodie with lightweight insulation.',
        imageUrl: 'https://m.media-amazon.com/images/I/51c+a9Yt1SL._AC_UY1100_.jpg',
        category: 'Fashion',
        stock: 80,
    },
    {
        id: 'p12',
        name: 'Adidas Ultraboost 23',
        brand: 'Adidas',
        price: 179.99,
        description: 'High-performance running shoes with responsive Boost cushioning.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeKanJ1qc-Lt48QJNzNPTrcT9TrA6Q8o1r4Q&s',
        category: 'Fashion',
        stock: 100,
    },
    {
        id: 'p13',
        name: 'Adidas Originals Track Pants',
        brand: 'Adidas',
        price: 59.99,
        description: 'Classic 3-stripe design slim-fit track pants.',
        imageUrl: 'https://m.media-amazon.com/images/I/71zEFmuy5oL._AC_UY1100_.jpg',
        category: 'Fashion',
        stock: 110,
    },
    {
        id: 'p14',
        name: 'Adidas Sweatshirt',
        brand: 'Adidas',
        price: 64.99,
        description: 'Soft fleece sweatshirt with logo detailing.',
        imageUrl: 'https://m.media-amazon.com/images/I/91u3UZrB8rL._AC_UY1100_.jpg',
        category: 'Fashion',
        stock: 85,
    },

    // 🔹 HOME & KITCHEN
    {
        id: 'p15',
        name: 'Apple HomePod Mini',
        brand: 'Apple',
        price: 99.99,
        description: 'Compact smart speaker with high-quality sound and Siri integration.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc1LnjVm3bJxxIQlVLQWRygyF4riR5XG5jyQ&s ',
        category: 'Home & Kitchen',
        stock: 70,
    },
    {
        id: 'p16',
        name: 'Samsung Smart Refrigerator',
        brand: 'Samsung',
        price: 2499.99,
        description: 'Family Hub refrigerator with touchscreen and Wi-Fi connectivity.',
        imageUrl: 'https://image-us.samsung.com/SamsungUS/home/home-appliances/refrigerators/06292022/rf29a9771sg/RF29A9771SG_01_Black_SCOM.jpg?$product-details-jpg$',
        category: 'Home & Kitchen',
        stock: 20,
    },
    {
        id: 'p17',
        name: 'Sony 4K Smart TV 55"',
        brand: 'Sony',
        price: 999.99,
        description: 'Ultra HD smart TV with HDR and Google TV built-in.',
        imageUrl: 'https://sharptronics.in/cdn/shop/products/81P7iSxFzzS._SL1500.jpg?v=1635746856',
        category: 'Home & Kitchen',
        stock: 50,
    },
    {
        id: 'p18',
        name: 'Samsung Microwave Oven',
        brand: 'Samsung',
        price: 249.99,
        description: 'Digital microwave oven with grill and convection modes.',
        imageUrl: 'https://images.samsung.com/is/image/samsung/p6pim/in/mc28a5025qb-tl/gallery/in-mc28a5025-convection-microwave--28-l-425064-mc28a5025qb-tl-534518480?$684_547_PNG$',
        category: 'Home & Kitchen',
        stock: 60,
    },
    {
        id: 'p19',
        name: 'Apple Smart LED Light',
        brand: 'Apple',
        price: 59.99,
        description: 'Wi-Fi-enabled smart light with adjustable brightness and color.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqhB4GZM8-gCy0_l4IuCInu3_TVHQmMp6nOg&s',
        category: 'Home & Kitchen',
        stock: 100,
    },
    {
        id: 'p20',
        name: 'Sony Bluetooth Speaker',
        brand: 'Sony',
        price: 129.99,
        description: 'Portable waterproof speaker with extra bass.',
        imageUrl: 'https://images.unsplash.com/photo-1603808033192-082d6919d26b?w=500',
        category: 'Home & Kitchen',
        stock: 90,
    },

    // 🔹 BEAUTY
    {
        id: 'p21',
        name: 'Apple AirTag Mirror Case',
        brand: 'Apple',
        price: 29.99,
        description: 'Stylish mirror case with AirTag slot for handbags.',
        imageUrl: 'https://images.unsplash.com/photo-1603354350317-6f7aaa5911c5?w=500',
        category: 'Beauty',
        stock: 150,
    },
    {
        id: 'p22',
        name: 'Samsung Hair Dryer',
        brand: 'Samsung',
        price: 89.99,
        description: 'Ionic hair dryer with smart temperature control.',
        imageUrl: 'https://media.wired.com/photos/60b00aee74ef4079779bcb10/1:1/w_1734,h_1734,c_limit/Gear-Hair-Dryers-Hairitige-Comin-Hot.jpg',
        category: 'Beauty',
        stock: 110,
    },
    {
        id: 'p23',
        name: 'Phillips Electric Shaver',
        brand: 'Phillips',
        price: 99.99,
        description: 'Rechargeable waterproof electric shaver for men.',
        imageUrl: 'https://www.seanhennessy.ie/image/thumbnails/1f/7d/S5898_25-128991-800x800.jpg',
        category: 'Beauty',
        stock: 70,
    },
    {
        id: 'p24',
        name: 'Nike Perfume Spray',
        brand: 'Nike',
        price: 39.99,
        description: 'Refreshing long-lasting fragrance for daily wear.',
        imageUrl: 'https://m.media-amazon.com/images/I/51zVHRUV8XL._AC_UF1000,1000_QL80_.jpg',
        category: 'Beauty',
        stock: 130,
    },
    {
        id: 'p25',
        name: 'Adidas Skin Care Lotion',
        brand: 'Adidas',
        price: 24.99,
        description: 'Hydrating skin lotion with natural extracts.',
        imageUrl: 'https://assets.ajio.com/medias/sys_master/root/20240311/AUOV/65eeee3216fd2c6e6a4cd705/-1117Wx1400H-4943967880-multi-MODEL.jpg',
        category: 'Beauty',
        stock: 150,
    },

    // 🔹 SPORTS
    {
        id: 'p26',
        name: 'Nike Running Shorts',
        brand: 'Nike',
        price: 34.99,
        description: 'Lightweight, breathable shorts for running and gym workouts.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc0zr5owPXzFyyzVeVw9OQsAtbgUGL-jVi4w&s',
        category: 'Sports',
        stock: 120,
    },
    {
        id: 'p27',
        name: 'Nike Yoga Mat',
        brand: 'Nike',
        price: 49.99,
        description: 'Non-slip yoga mat with soft cushioning for comfort.',
        imageUrl: 'https://images-eu.ssl-images-amazon.com/images/I/411JDyM+tML._AC_UL750_SR750,750_.jpg',
        category: 'Sports',
        stock: 140,
    },
    {
        id: 'p28',
        name: 'Adidas Football',
        brand: 'Adidas',
        price: 59.99,
        description: 'FIFA-approved football with premium grip and durability.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnkh1_RImtgcHnA-UV3feiwY8i6gYg_XUgtw&s',
        category: 'Sports',
        stock: 80,
    },
    {
        id: 'p29',
        name: 'Adidas Gym Bag',
        brand: 'Adidas',
        price: 54.99,
        description: 'Spacious sports duffel bag with shoe compartment.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSABpPhHPVd9W-AJvVCGqEgxEpQ-eO709dkZw&s',
        category: 'Sports',
        stock: 90,
    },
    {
        id: 'p30',
        name: 'Sony Sports Earbuds',
        brand: 'Sony',
        price: 99.99,
        description: 'Sweat-resistant wireless earbuds with deep bass for workouts.',
        imageUrl: 'https://assets.myntassets.com/w_412,q_30,dpr_3,fl_progressive,f_webp/assets/images/2147383/2017/10/30/11509359926212-Sony-Unisex-Headphones-8581509359926158-2.jpg',
        category: 'Sports',
        stock: 100,
    },
];


class ProductModel {
    static getAll() {
        return products;
    }

    static getById(id) {
        return products.find((p) => p.id === id);
    }

    static create(productData) {
        const newProduct = {
            id: `p${Date.now()}`,
            createdAt: new Date(),
            ...productData,
        };
        products.push(newProduct);
        return newProduct;
    }

    static exists(id) {
        return products.some((p) => p.id === id);
    }
}

module.exports = ProductModel;